
--Some query has modified for PostgreSQL like :
--1. BLOB changed to BYTEA.
/******************************************************************************/
/***                                Domains                                 ***/
/******************************************************************************/

CREATE DOMAIN DMADDRESS AS
VARCHAR(100); --CHARACTER SET WIN1251;

CREATE DOMAIN DMAPPIDUSER AS
VARCHAR(30);

CREATE DOMAIN DMBARCODE13 AS
CHAR(13);

CREATE DOMAIN DMBLOK AS
VARCHAR(4);-- CHARACTER SET WIN1251;

CREATE DOMAIN DMCKPASSPORT AS
VARCHAR(17);

CREATE DOMAIN DMCODEID AS
VARCHAR(4);

CREATE DOMAIN DMCODETYPEAPAR AS
VARCHAR(3);

CREATE DOMAIN DMDATALOG AS
VARCHAR(4000);

CREATE DOMAIN DMDATE AS
DATE;

CREATE DOMAIN DMDATETIME AS
TIMESTAMP;

CREATE DOMAIN DMDESCRIPTION AS
VARCHAR(500);

CREATE DOMAIN DMFLAG AS
SMALLINT;

CREATE DOMAIN DMFLAGC AS
CHAR(1);

CREATE DOMAIN DMGNPRODUCT AS
VARCHAR(15);

CREATE DOMAIN DMID AS
VARCHAR(36);

CREATE DOMAIN DMIDADDRESS AS
VARCHAR(15);

CREATE DOMAIN DMIDADJUSTMENT AS
VARCHAR(17);

CREATE DOMAIN DMIDANSWER AS
VARCHAR(15);

CREATE DOMAIN DMIDAP AS
VARCHAR(17);

CREATE DOMAIN DMIDAPP AS
VARCHAR(36);

CREATE DOMAIN DMIDAPPOBJECT AS
VARCHAR(36);

CREATE DOMAIN DMIDAR AS
VARCHAR(17);

CREATE DOMAIN DMIDASET AS
VARCHAR(30);-- CHARACTER SET WIN1251;

CREATE DOMAIN DMIDATRIBUTSTOK AS
VARCHAR(2);

CREATE DOMAIN DMIDATTENDANCE AS
VARCHAR(15);

CREATE DOMAIN DMIDBANK AS
VARCHAR(8);-- CHARACTER SET WIN1251;

CREATE DOMAIN DMIDBENTUK AS
VARCHAR(2);

CREATE DOMAIN DMIDCASHBANK AS
VARCHAR(15);

CREATE DOMAIN DMIDCASHFLOW AS
VARCHAR(17);

CREATE DOMAIN DMIDCATEGORY AS
VARCHAR(15);

CREATE DOMAIN DMIDCHEQUE AS
VARCHAR(17);

CREATE DOMAIN DMIDCITY AS
VARCHAR(5);-- CHARACTER SET WIN1251;

CREATE DOMAIN DMIDCOA AS
VARCHAR(15);

CREATE DOMAIN DMIDCOACATEGORY AS
VARCHAR(15);

CREATE DOMAIN DMIDCOMPANY AS
VARCHAR(15);

CREATE DOMAIN DMIDCOMPANYCODE AS
VARCHAR(4);

CREATE DOMAIN DMIDCOOPERATION AS
VARCHAR(15);

CREATE DOMAIN DMIDCOUNTRY AS
VARCHAR(5);-- CHARACTER SET WIN1251;

CREATE DOMAIN DMIDCUSTOMER AS
VARCHAR(15);-- CHARACTER SET WIN1251;

CREATE DOMAIN DMIDDEFAULT AS
VARCHAR(15);

CREATE DOMAIN DMIDDEPT AS
VARCHAR(15);-- CHARACTER SET WIN1251;

CREATE DOMAIN DMIDDISCOUNT AS
VARCHAR(15);

CREATE DOMAIN DMIDDIVISI AS
VARCHAR(15);

CREATE DOMAIN DMIDDOC AS
VARCHAR(15);

CREATE DOMAIN DMIDDOWNLINE AS
VARCHAR(5);-- CHARACTER SET WIN1251;

CREATE DOMAIN DMIDEDUCATION AS
VARCHAR(2);

CREATE DOMAIN DMIDEMPLOYEE AS
VARCHAR(30);

CREATE DOMAIN DMIDEMPMODULE AS
VARCHAR(15);

CREATE DOMAIN DMIDFAMILY AS
VARCHAR(15);

CREATE DOMAIN DMIDGOLONGAN AS
VARCHAR(5);

CREATE DOMAIN DMIDGROUP AS
VARCHAR(50);

CREATE DOMAIN DMIDHPP AS
VARCHAR(17);

CREATE DOMAIN DMIDINVENTORY AS
VARCHAR(15);

CREATE DOMAIN DMIDJENISASET AS
VARCHAR(2);-- CHARACTER SET WIN1251;

CREATE DOMAIN DMIDJENISSTOK AS
VARCHAR(2);-- CHARACTER SET WIN1251;

CREATE DOMAIN DMIDKAWASAN AS
VARCHAR(15);

CREATE DOMAIN DMIDKAWASANINDUK AS
VARCHAR(3);

CREATE DOMAIN DMIDLOCATION AS
VARCHAR(5);

CREATE DOMAIN DMIDMAIL AS
VARCHAR(17);

CREATE DOMAIN DMIDMANAGER AS
VARCHAR(2);

CREATE DOMAIN DMIDMENGHADAP AS
VARCHAR(2);-- CHARACTER SET WIN1251;

CREATE DOMAIN DMIDMENU AS
VARCHAR(30);

CREATE DOMAIN DMIDMODULE AS
VARCHAR(15);

CREATE DOMAIN DMIDMSG AS
VARCHAR(32)-- CHARACTER SET WIN1251
DEFAULT 00000000000000000000000000000000;

CREATE DOMAIN DMIDOUTLET AS
VARCHAR(15);

CREATE DOMAIN DMIDPAYMENTMODE AS
VARCHAR(15);

CREATE DOMAIN DMIDPERIOD AS
VARCHAR(15);

CREATE DOMAIN DMIDPO AS
VARCHAR(17);

CREATE DOMAIN DMIDPOSITION AS
VARCHAR(15);

CREATE DOMAIN DMIDPR AS
VARCHAR(17);

CREATE DOMAIN DMIDPRINTER AS
VARCHAR(15);

CREATE DOMAIN DMIDPRODUCT AS
VARCHAR(15);

CREATE DOMAIN DMIDPRODUCTION AS
VARCHAR(17);

CREATE DOMAIN DMIDPROJECT AS
VARCHAR(15);

CREATE DOMAIN DMIDQUESTION AS
VARCHAR(15);

CREATE DOMAIN DMIDQUESTIONNAIR AS
VARCHAR(15);

CREATE DOMAIN DMIDQUESTIONNAIRDT AS
VARCHAR(15);

CREATE DOMAIN DMIDQUESTIONNAIRE AS
VARCHAR(15);

CREATE DOMAIN DMIDRAWLAND AS
VARCHAR(36);-- CHARACTER SET WIN1251;

CREATE DOMAIN DMIDREFF AS
VARCHAR(30);

CREATE DOMAIN DMIDREPORT AS
VARCHAR(36);

CREATE DOMAIN DMIDROLE AS
VARCHAR(5);-- CHARACTER SET WIN1251;

CREATE DOMAIN DMIDSALES AS
VARCHAR(2);-- CHARACTER SET WIN1251;

CREATE DOMAIN DMIDSCHOOL AS
VARCHAR(5);

CREATE DOMAIN DMIDSERVER AS
VARCHAR(6);

CREATE DOMAIN DMIDSHIFT AS
VARCHAR(17);

CREATE DOMAIN DMIDSKILL AS
VARCHAR(15);

CREATE DOMAIN DMIDSPT AS
VARCHAR(17);

CREATE DOMAIN DMIDSTATE AS
VARCHAR(5);-- CHARACTER SET WIN1251;

CREATE DOMAIN DMIDSTOCK AS
VARCHAR(20);-- CHARACTER SET WIN1251;

CREATE DOMAIN DMIDSUPPLIER AS
VARCHAR(15);

CREATE DOMAIN DMIDSYSCOA AS
VARCHAR(30);

CREATE DOMAIN DMIDTAX AS
VARCHAR(2);

CREATE DOMAIN DMIDTEAMWORK AS
VARCHAR(15);

CREATE DOMAIN DMIDTEMPLATE AS
VARCHAR(36);

CREATE DOMAIN DMIDTEMPQUEST AS
VARCHAR(15);

CREATE DOMAIN DMIDTERMYN AS
VARCHAR(15);

CREATE DOMAIN DMIDTIPEPEMBATALANSPT AS
VARCHAR(1);

CREATE DOMAIN DMIDTIPEPERUBAHANSPT AS
VARCHAR(1);-- CHARACTER SET WIN1251;

CREATE DOMAIN DMIDTIPESTOK AS
VARCHAR(7);

CREATE DOMAIN DMIDTRAINING AS
VARCHAR(5);

CREATE DOMAIN DMIDTYPEAPAR AS
VARCHAR(17);

CREATE DOMAIN DMIDUOM AS
VARCHAR(15);

CREATE DOMAIN DMIDUSER AS
VARCHAR(30);-- CHARACTER SET WIN1251;

CREATE DOMAIN DMIDVIEW AS
VARCHAR(2);

CREATE DOMAIN DMIDWAREHOUSE AS
VARCHAR(15);

CREATE DOMAIN DMIDWHDB AS
VARCHAR(17);

CREATE DOMAIN DMIDWORKING AS
VARCHAR(15);

CREATE DOMAIN DMIM_DTID AS
VARCHAR(19);

CREATE DOMAIN DMIM_HDID AS
VARCHAR(17);

CREATE DOMAIN DMIM_IDAPPEND AS
VARCHAR(33);

CREATE DOMAIN DMIM_IDNULL AS
VARCHAR(33);

CREATE DOMAIN DMINCKEY AS
INTEGER;

CREATE DOMAIN DMINITIAL AS
VARCHAR(3);

CREATE DOMAIN DMISFLAG AS
INTEGER
NOT NULL;

CREATE DOMAIN DMMAILCODE AS
VARCHAR(5);

CREATE DOMAIN DMMESSAGE AS
VARCHAR(160);-- CHARACTER SET WIN1251;

CREATE DOMAIN DMMONEY AS
DOUBLE PRECISION;

CREATE DOMAIN DMMONTH AS
SMALLINT;

CREATE DOMAIN DMNAME AS
VARCHAR(50);

CREATE DOMAIN DMNIP AS
VARCHAR(30);

CREATE DOMAIN DMNOADJUSTMENT AS
VARCHAR(30);

CREATE DOMAIN DMNOAP AS
VARCHAR(30);

CREATE DOMAIN DMNOAR AS
VARCHAR(30);

CREATE DOMAIN DMNOJOURNAL AS
VARCHAR(30);

CREATE DOMAIN DMNOKAVLING AS
VARCHAR(4);-- CHARACTER SET WIN1251;

CREATE DOMAIN DMNOKTP AS
VARCHAR(20);-- CHARACTER SET WIN1251;

CREATE DOMAIN DMNOKWITANSI AS
VARCHAR(50);

CREATE DOMAIN DMNOPRODUCTION AS
VARCHAR(30);

CREATE DOMAIN DMNOSPT AS
VARCHAR(30);-- CHARACTER SET WIN1251;

CREATE DOMAIN DMNOVOUCHER AS
VARCHAR(30);

CREATE DOMAIN DMPASSWORD AS
VARCHAR(10);

CREATE DOMAIN DMPHONENO AS
VARCHAR(20);-- CHARACTER SET WIN1251;

CREATE DOMAIN DMPOSBILLINGPREFIX AS
VARCHAR(3);

CREATE DOMAIN DMPOSCDESCRIPTION AS
VARCHAR(50);

CREATE DOMAIN DMPOSCENTRYBY AS
VARCHAR(20);

CREATE DOMAIN DMPOSCIDFKNOTNULL AS
VARCHAR(15);

CREATE DOMAIN DMPOSCIDFKNOTNULL17 AS
VARCHAR(17);

CREATE DOMAIN DMPOSCIDFKNULL AS
VARCHAR(15);

CREATE DOMAIN DMPOSCIDFKNULL17 AS
VARCHAR(17);

CREATE DOMAIN DMPOSCIDSETUP AS
VARCHAR(15);

CREATE DOMAIN DMPOSCIDSETUPNULL AS
VARCHAR(15);

CREATE DOMAIN DMPOSCIDTRANS AS
VARCHAR(15);

CREATE DOMAIN DMPOSCIDTRANS17 AS
VARCHAR(17);

CREATE DOMAIN DMPOSCUPDATEBY AS
VARCHAR(20);

CREATE DOMAIN DMPOSCVARCHAR30 AS
VARCHAR(30);

CREATE DOMAIN DMPOSCVARCHAR500 AS
VARCHAR(500);

CREATE DOMAIN DMPOSDENTRY AS
TIMESTAMP
DEFAULT 'now';

CREATE DOMAIN DMPOSDTRANS AS
TIMESTAMP;

CREATE DOMAIN DMPOSDTRANSNULL AS
TIMESTAMP;

CREATE DOMAIN DMPOSDUPDATE AS
TIMESTAMP;

CREATE DOMAIN DMPOSNDISCOUNT AS
DOUBLE PRECISION
DEFAULT 0;

CREATE DOMAIN DMPOSNDISCOUNTPERCENT AS
FLOAT
DEFAULT 0;

CREATE DOMAIN DMPOSNFLAG0 AS
INTEGER
DEFAULT 0;

CREATE DOMAIN DMPOSNFLAG1 AS
INTEGER
DEFAULT 1;

CREATE DOMAIN DMPOSNMONEY AS
DOUBLE PRECISION
DEFAULT 0;

CREATE DOMAIN DMPOSNPRICE AS
DOUBLE PRECISION
DEFAULT 0;

CREATE DOMAIN DMPOSNQTY AS
FLOAT
DEFAULT 0;

CREATE DOMAIN DMPOSNSERVICE AS
DOUBLE PRECISION
DEFAULT 0;

CREATE DOMAIN DMPOSNSERVICEPERCENTAGE AS
FLOAT
DEFAULT 0;

CREATE DOMAIN DMPOSNSTATUS AS
INTEGER
DEFAULT 0;

CREATE DOMAIN DMPOSNTAX AS
DOUBLE PRECISION
DEFAULT 0;

CREATE DOMAIN DMPOSNTAXPERCENTAGE AS
FLOAT
DEFAULT 0;

CREATE DOMAIN DMPRODUCTCODE AS
VARCHAR(20);

CREATE DOMAIN DMREPORTFILE AS
BYTEA;

CREATE DOMAIN DMRTRW AS
VARCHAR(4);-- CHARACTER SET WIN1251;

CREATE DOMAIN DMSHORTCOMPANY AS
VARCHAR(3);

CREATE DOMAIN DMSHORTKAWASAN AS
VARCHAR(3);

CREATE DOMAIN DMSHORTPROJECT AS
VARCHAR(3);

CREATE DOMAIN DMSPK AS
VARCHAR(30);

CREATE DOMAIN DMSYSID AS
VARCHAR(32);

CREATE DOMAIN DMSYSLONGID AS
VARCHAR(150)
NOT NULL;

CREATE DOMAIN DMSYSNO AS
VARCHAR(50);

CREATE DOMAIN DMTEXT10 AS
VARCHAR(10);

CREATE DOMAIN DMTEXT100 AS
VARCHAR(100);-- CHARACTER SET WIN1251;

CREATE DOMAIN DMTEXT1000 AS
VARCHAR(1000);

CREATE DOMAIN DMTEXT10K AS
VARCHAR(10000);

CREATE DOMAIN DMTEXT2 AS
VARCHAR(2);

CREATE DOMAIN DMTEXT200 AS
VARCHAR(200);-- CHARACTER SET WIN1251;

CREATE DOMAIN DMTEXT2000 AS
VARCHAR(2000);

CREATE DOMAIN DMTEXT250 AS
VARCHAR(250);

CREATE DOMAIN DMTEXT30 AS
VARCHAR(30);

CREATE DOMAIN DMTEXT300 AS
VARCHAR(300);

CREATE DOMAIN DMTEXT30K AS
VARCHAR(30000);

CREATE DOMAIN DMTEXT50 AS
VARCHAR(50);

CREATE DOMAIN DMTEXT500 AS
VARCHAR(500);

CREATE DOMAIN DMTEXT5000 AS
VARCHAR(5000);

CREATE DOMAIN DMTEXT_DT AS
VARCHAR(250);

CREATE DOMAIN DMTIME AS
TIME;

CREATE DOMAIN DMTIMESTAMP AS
TIMESTAMP;

CREATE DOMAIN DMTRANSDATE AS
DATE;

CREATE DOMAIN DMTRANSNO AS
VARCHAR(50);

CREATE DOMAIN DMUKURAN AS
DOUBLE PRECISION;

CREATE DOMAIN DMUSERCODE AS
VARCHAR(32);

CREATE DOMAIN DMWHCLOSING AS
VARCHAR(17);

CREATE DOMAIN DMYEAR AS
SMALLINT;

CREATE DOMAIN DMZIPCODE AS
VARCHAR(6);-- CHARACTER SET WIN1251;

CREATE DOMAIN DM_3CODE AS
VARCHAR(3);

CREATE DOMAIN DM_ADDRESS AS
VARCHAR(5000);

CREATE DOMAIN DM_BARCODE AS
VARCHAR(200);

CREATE DOMAIN DM_BIGINT AS
BIGINT
DEFAULT 0;

CREATE DOMAIN DM_BOOL AS
SMALLINT
DEFAULT 0;

CREATE DOMAIN DM_CASHBANK AS
VARCHAR(250);

CREATE DOMAIN DM_CITY AS
VARCHAR(255);

CREATE DOMAIN DM_COA AS
VARCHAR(250);

CREATE DOMAIN DM_COUNTRY AS
VARCHAR(250)
NOT NULL;

CREATE DOMAIN DM_COUNTRYREFF AS
VARCHAR(250);

CREATE DOMAIN DM_CURR AS
DECIMAL(18,2);

CREATE DOMAIN DM_CURR4 AS
DECIMAL(18,4)
DEFAULT 0;

CREATE DOMAIN DM_CURR8 AS
DECIMAL(18,8)
DEFAULT 0;

CREATE DOMAIN DM_CURRENCY AS
VARCHAR(250)
NOT NULL;

CREATE DOMAIN DM_CURRENCYREFF AS
VARCHAR(250);

CREATE DOMAIN DM_DATE AS
DATE;

CREATE DOMAIN DM_DATETIME AS
TIMESTAMP;

CREATE DOMAIN DM_DELIVERYMETHOD AS
VARCHAR(250);

CREATE DOMAIN DM_DEPTH AS
SMALLINT
DEFAULT 0
NOT NULL;

CREATE DOMAIN DM_DOUBLE AS
DOUBLE PRECISION
DEFAULT 0;

CREATE DOMAIN DM_EMAIL AS
VARCHAR(250);

CREATE DOMAIN DM_FLAG AS
SMALLINT
DEFAULT 0;

CREATE DOMAIN DM_GENDER AS
SMALLINT
DEFAULT 0
NOT NULL;

CREATE DOMAIN DM_INT AS
INTEGER
NOT NULL;

CREATE DOMAIN DM_INTEGER AS
INTEGER;

CREATE DOMAIN DM_MANCODE AS
VARCHAR(50);

CREATE DOMAIN DM_MANNO AS
VARCHAR(250);

CREATE DOMAIN DM_MONEY AS
DOUBLE PRECISION;

CREATE DOMAIN DM_MONEYREFF AS
DECIMAL(18,2);

CREATE DOMAIN DM_NAME AS
VARCHAR(255);

CREATE DOMAIN DM_OBSOLETE AS
SMALLINT
DEFAULT 0
NOT NULL;

CREATE DOMAIN DM_PASSWORD AS
VARCHAR(250)
NOT NULL;

CREATE DOMAIN DM_PERCENT AS
DECIMAL(10,4)
DEFAULT 0
NOT NULL;

CREATE DOMAIN DM_PHONE AS
VARCHAR(250);

CREATE DOMAIN DM_PRINTNAME AS
VARCHAR(1000);

CREATE DOMAIN DM_QTY AS
DOUBLE PRECISION
DEFAULT 0
NOT NULL;

CREATE DOMAIN DM_REFFNO AS
VARCHAR(250);

CREATE DOMAIN DM_SEQUENCE AS
INTEGER
DEFAULT 0
NOT NULL;

CREATE DOMAIN DM_SERVER AS
VARCHAR(6);

CREATE DOMAIN DM_SERVERREFF AS
VARCHAR(6);

CREATE DOMAIN DM_SIZE AS
DECIMAL(18,8);

CREATE DOMAIN DM_STATE AS
VARCHAR(255);

CREATE DOMAIN DM_STATUS AS
SMALLINT
DEFAULT 0;

CREATE DOMAIN DM_SYSCODE AS
VARCHAR(50);

CREATE DOMAIN DM_SYSDEFAULT AS
SMALLINT
DEFAULT 0
NOT NULL;

CREATE DOMAIN DM_SYSID AS
VARCHAR(32)
NOT NULL;

CREATE DOMAIN DM_SYSIDREFF AS
VARCHAR(32);

CREATE DOMAIN DM_SYSNO AS
VARCHAR(250);

CREATE DOMAIN DM_SYSPERSONTYPE AS
SMALLINT;

CREATE DOMAIN DM_TERMYN AS
VARCHAR(250)
NOT NULL;

CREATE DOMAIN DM_TEXT AS
VARCHAR(5000);

CREATE DOMAIN DM_TEXT5K AS
VARCHAR(5000);

CREATE DOMAIN DM_TEXTDT AS
VARCHAR(250);

CREATE DOMAIN DM_TEXTHD AS
VARCHAR(5000);

CREATE DOMAIN DM_TIME AS
TIME;

CREATE DOMAIN DM_UOMID AS
VARCHAR(32);

CREATE DOMAIN DM_USER AS
VARCHAR(250)
NOT NULL;

CREATE DOMAIN DM_USERREFF AS
VARCHAR(250);

CREATE DOMAIN DM_VALUE AS
DOUBLE PRECISION;



/******************************************************************************/
/***                              Descriptions                              ***/
/******************************************************************************/

COMMENT ON DOMAIN DM_SYSPERSONTYPE IS
'0 = NOT SET
1 = CUSTOMER
2 = SUPPLIER
3 = EMPLOYEE';
